- hosts: all
  gather_facts: False
  vars:
    python_version: "3.6.7"

  tasks:
  - name: install python 2
    become: True
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: ixypy development Environment
  hosts: all
  gather_facts: True
  tasks:
    - name: Update and Upgrade
      become: True
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    # - name: Add additional repositories
    #   become: True
    #   apt_repository:
    #     repo: ppa:jonathonf/python-3.6
    #     state: present

    - name: Install tools
      become: True
      apt:
        name: "{{ item }}"
        # update_cache: True
      with_items:
        - make
        - cmake
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - pciutils
        - vim
        - git

    - name: Install Python3
      become: True
      shell: |
        wget https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz
        tar xvf Python-3.6.7.tgz
        cd Python-3.6.7
        ./configure --enable-optimizations
        make -j8
        sudo make altinstall

    - name: Install pypy3
      become: True
      shell: |
        wget -q -P /tmp https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux64.tar.bz2
        sudo tar -x -C /opt -f /tmp/pypy3-v6.0.0-linux64.tar.bz2
        rm /tmp/pypy3-v6.0.0-linux64.tar.bz2
        sudo mv /opt/pypy3-v6.0.0-linux64 /opt/pypy3
        sudo ln -fs /opt/pypy3/bin/pypy3 /usr/bin/pypy3

    - name: Install pip3.6
      become: True
      shell: |
        wget https://bootstrap.pypa.io/get-pip.py
        python3.6 get-pip.py

    - name: Install python dependencies
      become: True
      pip:
        name: "{{ item }}"
        extra_args: -i https://pypi.python.org/simple
        executable: pip3
      with_items:
        - tox
        - pytest
        - cython

    # - name: Checkout ixy
    #   become: True
    #   git:
    #     repo: https://github.com/emmericp/ixy
    #     dest: /home/vagrant/ixy

    - name: Build ixy
      become: True
      shell: |
        sudo -u vagrant git clone https://github.com/emmericp/ixy /home/vagrant/ixy
        cd /home/vagrant/ixy
        if dmidecode -t 0 | grep VirtualBox ; then
          git checkout virtualbox-workarounds
        fi
        sudo -u vagrant cmake .
        sudo -u vagrant make
